### ISSUE TITLE
Feature Request: ability to hide/unhide MIDI devices

### ISSUE THREAD

**Issue by TheAndyMac** [gbevin/ShowMIDI#1]
Love the idea here and it is really useful alongside other MIDI monitors that provide the data streams.

To cope with monitoring multiple controllers, many of which can present multiple MIDI devices (in some cases up to 4 devices) it would be really helpful if there were a way to switch individual MIDI port monitoring on/off - maybe through an expandable left-hand folder list approach on the left (or right) with check boxes for enabled, or alternatively some form of dialog box from the menu.

As a further enhancement, it would be really good if you could have multiple "favourite" collections (presets if you like) of MIDI inputs available, so you could easily recall a setup to look at one/more instruments/controllers easily without having to select individual MIDI ports to enable/disable them.

Also the "hide" option should ideally disconnect from the specific MIDI devices to cope with the situation where a MIDI device is already connected to say a virtual MIDI device and, on Windows with the normal driver (not multi-client capable) this can cause connection issues.

**Comment by gbevin** [comment]
Thanks for the suggestions, I will definitely add a way to hide MIDI ports.

**Comment by gbevin** [comment]
Added in the new 0.5.0 release
