### ISSUE TITLE
Can we add the Mac release to homebrew?

### ISSUE THREAD

**Issue by fadersolo** [gbevin/ShowMIDI#10]
I'd love to be able to automatically grab latest releases thru homebrew.

**Comment by gbevin** [comment]
I've sadly not found a way to install a GUI app through homebrew.

**Comment by fadersolo** [comment]
GUI apps are called “Casks”. There’s instructions on this page: https://docs.brew.sh/Adding-Software-to-Homebrew#casks

I’ve managed to add an app once before -- but it was a journey and I promptly forgot everything I learned. Anyways, I’m trying to read thru this all again see if I can submit it myself.

**Comment by gbevin** [comment]
I have a homebrew repo this can be added to if you got something working https://github.com/gbevin/homebrew-tools

**Comment by fadersolo** [comment]
Ok, I’ve got a formula that successfully installs and uninstalls, but when I run `brew audit --new-cask showmidi` I get an error:

```
audit for showmidi: failed
 - GitHub repository too new (<30 days old)
 ```

LOL! So, I suppose I’ll try this again in a month?

Here’s the contents of showmidi.rb:
```
cask "showmidi" do
  version "0.5.1"
  sha256 "20699eee1c84a819abf9fbdb5c4d4a60698b7501a508448f293f3c563136347e"

  url "https://github.com/gbevin/ShowMIDI/releases/download/#{version}/ShowMIDI-macOS-#{version}.zip"
  name "ShowMIDI"
  desc "A multi-platform GUI application to effortlessly visualize MIDI activity"
  homepage "https://github.com/gbevin/ShowMIDI"

  pkg "ShowMIDI-#{version}.pkg"

  uninstall pkgutil: [
    "com.uwyn.ShowMIDI-LV2-1",
    "com.uwyn.ShowMIDI-CLAP-1",
    "com.uwyn.ShowMIDI-VST",
    "com.uwyn.ShowMIDI",
    "com.uwyn.ShowMIDI-VST3",
    "com.uwyn.ShowMIDI-AU",
  ]
end
```


I’ve left out the livecheck section. The last time I submitted an app, whichever maintainer checked my submit created a livecheck formula, so I assume it’s best left to the pros, but if you wanna figure that out here’s the [documentation](https://docs.brew.sh/Brew-Livecheck).

**Comment by gbevin** [comment]
Thanks so much, it's now live!
`brew install --cask gbevin/tools/showmidi`

**Comment by fadersolo** [comment]
Works on my end! Thank you again. :)
