### ISSUE TITLE
Sidebar open / close symbol may be reversed

### ISSUE THREAD

**Issue by riban-bw** [gbevin/ShowMIDI#15]
Running version 0.7.0 the sidebar can be shown by pressing the "<<" button and hidden by pressing the ">>" button. This feels reversed to me. I would expect the button to display the action it takes, i.e. ">>" to open and "<<" to close. This is on Linux.

**Comment by gbevin** [comment]
The icons display current state, same for the device visibility or play/pause one. "<<" is displayed when the sidebar is collapsed, pressing it will expand it, displaying the new state ">>".
