### ISSUE TITLE
Feature request: Allow monitoring of virtual MIDI signals

### ISSUE THREAD

**Issue by riban-bw** [gbevin/ShowMIDI#16]
The current version (0.7.0) allows monitoring of the MIDI inputs. It may be advantageous to allow monitoring of other points in the MIDI chain, e.g.

`MIDI Input>>A>>Processor>>B>>MIDI Output`

It would be good to be able to monitor at points 'A' & 'B' (and ideally also at MIDI Output. This is invaluable when tracing issues with MIDI signal within the host. It may benefit from being configurable so that you are not inundated with sources but can enable _internal sources_ as required.

This may be challenging due to the different MIDI / audio subsystems used in different (or even the same) systems / platforms, e.g. Linux may be using ALSA, JACK, Pipewire, etc. for MIDI signal routing.

**Comment by gbevin** [comment]
This is not planned. There are plugin versions to use in hosts and DAWs, in order to be able to insert into any location of the graph. The standalone version only looks at MIDI input devices.
