### ISSUE TITLE
Does not play nicely with audio subsystems

### ISSUE THREAD

**Issue by riban-bw** [gbevin/ShowMIDI#17]
Some operating systems implement audio subsystems that expect to have control of the audio / MIDI ports, e.g. JACK on Linux. If such a subsystem is running then ShowMIDI fails to show MIDI messages.

Example: Linux running JACK2. ShowMIDI will start and detect the physical MIDI inputs, showing them in its GUI but no MIDI messages are displayed. Stopping JACK2 and restarting ShowMIDI allows it to show received MIDI messages.

**Comment by gbevin** [comment]
Not much I can do about this, ShowMIDI relies on the infrastructure that JUCE provides and abstracts for each operating system.

**Comment by riban-bw** [comment]
JUCE does support JACK. If I get a chance I may take a look at how it might be integrated.

**Comment by gbevin** [comment]
Oh, I didn't know that, had a Quick Look and it's a flag to set in the ProJucer.

However, I think that will require every Linux install that used ShowMIDI to have Jack installed.
