### ISSUE TITLE
Feature request: Reset theme

### ISSUE THREAD

**Issue by riban-bw** [gbevin/ShowMIDI#18]
The "Random" theme generator can create some wacky colour combinations. It would be advantageous to be able to reset to the default theme. You cannot do so by restarting the app because the theme is persistent through restarts.

**Comment by riban-bw** [comment]
I see that there are some themes available to load but the "load" theme button does not take you to the folder containing these themes by default.

**Comment by gbevin** [comment]
Guess now that I have an installer, I could install the themes, good callout.

I was also considering adding a reset theme button, it's high on the todo.

**Comment by gbevin** [comment]
Implemented reset theme for the next release
