### ISSUE TITLE
Note numbering?

### ISSUE THREAD

**Issue by agraef** [gbevin/ShowMIDI#2]
Thanks a lot for this program, I love it! Simple and straightforward.

My only minor quibble is that having middle C = C2 is not very common. [IPN](https://en.wikipedia.org/wiki/Scientific_pitch_notation) (a.k.a "scientific pitch notation") seems to be the most common standard and has middle C = C4. Maybe you could change DEFAULT_OCTAVE_MIDDLE_C in MidiDeviceComponent.cpp accordingly? Or is there a reason that you've chosen this particular numbering of the octaves?

**Comment by gbevin** [comment]
Yeah I plan to make it configurable, I just had it set to what worked with Animoog's build-in keyboard and realized later that I should have gone for a more common one by default.

**Comment by gbevin** [comment]
I've set it back to being 3, which is the default in SendMIDI and ReceiveMIDI, and included that in release 0.2.0. I'll make this configurable in a future release.
https://github.com/gbevin/ShowMIDI/releases/tag/0.2.0

**Comment by gbevin** [comment]
Made this configurable in the new 0.5.0 release.

**Comment by agraef** [comment]
Thanks! C3 seems perfectly reasonable and is also a fairly common standard.

I'll update my AUR package at https://aur.archlinux.org/packages/showmidi later today. Once ShowMIDI stabilizes, I can ask David Runge to adopt it so that it goes into the official Arch package repository.

**Comment by agraef** [comment]
Wow, this has come along nicely! AUR package is updated. Tested the VST3 in Bitwig Studio, and both LV2 and VST3 in Ardour, all working nicely. (I didn't package the VST2 for license reasons.)

**Comment by gbevin** [comment]
Awesome, thank you!
