### ISSUE TITLE
Feature request: Support for 14-bit CC

### ISSUE THREAD

**Issue by scztt** [gbevin/ShowMIDI#23]
ShowMIDI currently displays 14-bit CC signals as two separate controls (which is correct insofar as this is how these are transmitted, but of course not useful for the intended purpose).

At a minimum, a 14 bit cc feature would entail creating a list of pairs of CC numbers that represent a combined 14-bit control, plus specifying whether the device is sending the least or most significant bits first.

A more usable + helpful version of this feature would simply detect streams of CC data that *look* like 14-bit CC, and offer an option to interpret these as 14 bit automatically. This should be straightforward - 14-bit CC messages should always come in ordered pairs at the same time, with one value that tends toward small deltas and one with large / semi-random deltas.

**Comment by gbevin** [comment]
I don't want to add a GUI to configure possible matching pairs. However what I did plan already was to add support for CC 0-31 MSB and 32-63 LSB pairs.

Your description of messages that look like 14 bit isn't fully correct though, it's not necessary to resend the MSB all the time, fine changes can be done with just the LSB until an adjustment needs the MSB to be resent to reach different numbers.
