### ISSUE TITLE
FR: Show note on velocity post note off 

### ISSUE THREAD

**Issue by sudara** [gbevin/ShowMIDI#25]
Hi Geert! 

Really thankful to be able to use such a high quality free utility — and one that looks nice! <3

Wondering if it would be possible to persist Note On velocity somewhere. I'm assuming my controller is sending Note Off with a velocity of 0 —  so when notes are quick, it's a bit tough to inspect velocity. A hacky solution you may not like would be to display `0 (127)` or something on Note Off, or still show `ON 127` above the note off?

https://github.com/gbevin/ShowMIDI/assets/472/28b1af2a-e963-4e2f-bdbe-d32e244ca5ca

Related huge "what if" feature request that you should 100% definitely ignore (but if you gave me some indication of interest, i could try to submit a PR) — it might be really nice to see a channel / note independent histogram of velocity, CP, CC 74, etc...

**Comment by gbevin** [comment]
Hi, thanks for the suggestion, it's definitely something that could be improved but it's a challenge to make it look the right way, I'll give it some thought.

**Comment by gbevin** [comment]
FYI the 0 or 127 on Note Off is the release velocity, it can have different values on controllers that support it

**Comment by gbevin** [comment]
If you can build from source, I pushed an improvement to this. Here's a screenshot of what it looks like. I would like to get some other enhancement requests in there before a next public release though.

<img width="300" alt="Screenshot 2024-01-02 at 18 32 20" src="https://github.com/gbevin/ShowMIDI/assets/701148/14a651c2-2590-45a8-902e-52e0952f92df">

**Comment by sudara** [comment]
Wow, ridiculous turnaround! Yes, I built it and it works great. (I'm exploring some stuff re: velocity curves, so this is quite helpful as a starting place!)
