### ISSUE TITLE
Ordering by most recent note on (vs. ascending channel number)

### ISSUE THREAD

**Issue by sudara** [gbevin/ShowMIDI#26]
Pushing my luck here, but I'm wondering if an incoming new note could always populate the top slot? 

Notes are ordered by channel right now, which means things can feel "jumpy" (not always clear where the latest note is when there's a larger list) but also, if i hit a few notes, it often requires scrolling to see the latest note on. If new notes always populated the top slot, one could always focus attention in the same top spot (and it would smooth overall motion to some degree).

I'm guessing the channel ordering is in part because notes are grouped by channel (can be multiple things per channel happening) so perhaps this is non-trivial / would require the whole channel group to be repositioned?...

**Comment by gbevin** [comment]
It's one of the design decisions I've made, everything is always ordered the same way and slotted into buckets, otherwise you eventually end up with the per-message granularity of regular midi loggers.

**Comment by sudara** [comment]
Ok, it makes sense that buckets are channels. I guess the feature request would be ordering the buckets by last modified item, but sounds like that's undesirable! Maybe a good excuse for me to get a monitor in vertical orientation again 😈
