### ISSUE TITLE
ShowMIDI is available as MIDI FX Plugin in Logic, but doesn't show any events

### ISSUE THREAD

**Issue by beely** [gbevin/ShowMIDI#27]
You can call up ShowMIDI (Mac/AU version) as a MIDI FX plugin in Logic in the MIDI FX insert slot.

It opens, displays a window, but never shows any MIDI events, whether incoming in realtime, or via the track playback - both sources of MIDI data should be passing through the plugin.

Is this supposed to work? Presumably the app has been compiled to be available as a MIDI Plugin in Logic for a reason, or maybe I'm doing something wrong...?

**Comment by gbevin** [comment]
This requires specific Logic setup, MIDI is not passed through to MIDI FX on a channel unless there's a MIDI Instrument on the track.
