### ISSUE TITLE
Icon is a little larger than the standard MacOS size.

### ISSUE THREAD

**Issue by weskoop** [gbevin/ShowMIDI#30]
Super minor, the app Icon is a bit large compared to others, at least on Sonoma. It could be a more recent MacOS thing, I don't have an older mac to verify.

For Example: 
<img width="581" alt="Screenshot 2024-01-24 at 4 31 39 PM 1" src="https://github.com/gbevin/ShowMIDI/assets/543051/8826164e-4cbf-4256-94bd-4fcecb178576">

**Comment by gbevin** [comment]
Fixed
