### ISSUE TITLE
Reaper put it into failed to scan list

### ISSUE THREAD

**Issue by CodesoundR** [gbevin/ShowMIDI#31]
Linux Mint 21.3 Cinnamom_x64 - Reaper 7.11 - ShowMIDI 0.9.0

Hi and thanks for tgis project!
I don't undestand why Reaper failed to scan the ShowMIDI.clap How can I fix it?

https://imgur.com/jgoZSuK

greet

**Comment by gbevin** [comment]
I can't reproduce this, it works fine on my linux machines.
