### ISSUE TITLE
New signing issue with 0.9.0 Windows binary?

### ISSUE THREAD

**Issue by timg11** [gbevin/ShowMIDI#33]
I read that  as of 0.7.0     Windows builds are now fully code signed

I just tried to install ShowMIDI-Windows-0.9.0.exe   (5,099,792 bytes) signed by `Open Source Developer, Geert Bevin`
and it gives this error:

`"Windows protected your PC - Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk. "  `

Is this a regression in the signing, or is there another issue with 0.9.0?

**Comment by gbevin** [comment]
This was the binary not having sufficient 'reputation' with Microsoft yet. I contacted Microsoft. It has now established the necessary reputation and when updating the SmartScreen definitions and re-downloading the binary, the warning doesn't appear anymore.
