### ISSUE TITLE
Linux missing libraries

### ISSUE THREAD

**Issue by critchie** [gbevin/ShowMIDI#34]
Love the app on MacOS and would like to get it running on Linux where I do a lot of my device development.

I'm running LMDE6 and when I try to run ShowMIDI I get these errors:

./ShowMIDI: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./ShowMIDI)
./ShowMIDI: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by ./ShowMIDI)
./ShowMIDI: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./ShowMIDI)

I'm kind of new to Linux and know enough to be dangerous. What do I need to install to get these libraries on my system?

Or better yet... maybe a Flatpak can be made available.

**Comment by gbevin** [comment]
There's not much I can do about this. Each distribution typically compiles and packages their own version with the installed libraries. I've included instructions in the readme on how to build it from source yourself. Otherwise please ask your Linux distribution.

**Comment by critchie** [comment]
Building from source got it all worked out. Thanks.
