### ISSUE TITLE
Compact / Multi NRPN display

### ISSUE THREAD

**Issue by RadekPilich** [gbevin/ShowMIDI#36]
Follow up from my YouTube comment, I would like to suggest improvement for the display of NRPN controllers.
1. Display each controller individually rather than jumping from one to another
2. Provide alternative display format to make it obvious it's single NRPN controller and not three CC controllers

Original comment: "Could you provide setting for alternate NRPN display, where the unique CC 98 and 99 combinations would be merged together into one visualization slot together with the actual CC 6 value? Right now, not only is it a bit unintuitive, but it is not possible to monitor multiple NRPN controllers (knobs) at the same time."

Video demonstration: https://www.youtube.com/watch?v=KArrbf8KxNM

**Comment by gbevin** [comment]
Hi, thanks for the report. I think I fixed this in the source code since your YouTube comment. Your video is private, I can't see it. Which device are you using?

**Comment by RadekPilich** [comment]
Video visibility fixed, sorry, didn't notice. Details in video - Faderfox EC4 with my mapping for the FX unit on Novation Summit.

**Comment by gbevin** [comment]
Should be fixed in shortly available 1.0.1 release

**Comment by gbevin** [comment]
Release available here https://github.com/gbevin/ShowMIDI/releases/tag/1.0.1
