### ISSUE TITLE
VST3 on windows / ableton live wont load

### ISSUE THREAD

**Issue by tastez** [gbevin/ShowMIDI#38]
Anyone else having issues with vst3 opening in ableton live? i just get an error after placing the vst on a track. It shows up in the plugin browser correctly and directory structure seems ok.

VST seems to load and works!

some notes: 
standalone version is not running
pc not rebooted after install

system
win 11 pro

tested on:
Ableton live 12.1 and 12

**Comment by gbevin** [comment]
In Live it loads for me but doesn't show any MIDI, while it loads in any other DAW on Windows. Have you tried loading it in other DAWs, like Reaper or BitWig? What happens when you launch the standalone version, I've not had any reports of the standalone version not running.

**Comment by tastez** [comment]
Bitwig 5.1 VST3 works! 
interesting!
MaxMSP VST3 works also..what the heck..

All good with standalone on win11 pro here i can see all my midi devices and it works as expected.

**Comment by gbevin** [comment]
I think it's an issue with Live and MIDI processor plugins, please report it to Ableton.

**Comment by tastez** [comment]
will do - interesting that only vst3 is affected!
best!
