### ISSUE TITLE
Feature request: WebMidi version

### ISSUE THREAD

**Issue by iplanwebsites** [gbevin/ShowMIDI#43]
Fantastic little app! Congrats on the award nomination.
It'd be a big rewrite of the UI, but it'd be great to move the logic to a WebUi for better accessibility.
All the other midi testers online are pretty limited, and I believe it wouldn't be too hard to replicate a the UI on the web.
Libs like tonal.js would also make it easy to handle music theory data (frequency, note names, etc)

**Comment by gbevin** [comment]
Thanks for the suggestion, I have no plans to make a web midi version, sorry.

**Comment by iplanwebsites** [comment]
For anyone searching here, I created a [web-app version of ShowMIDI called MIDI Mama](https://github.com/AuraTown/MidiMama).
It's a WIP but replicate the core functionalities.
