### ISSUE TITLE
Feature: Option for the timeout on CC and pitchbend to be unbounded

### ISSUE THREAD

**Issue by essej** [gbevin/ShowMIDI#6]
An option for the timeout on CC and pitchbend (at least) to be unbounded would be very useful. So that the current state of those can always be visible... since they actually have persistent state in the real world of midi instruments/devices. You can add a reset/clear button per midi device so it can be manually cleared on demand. When that's on some other visual indication can let the user know if it is "old" via text/background intensity.

**Comment by gbevin** [comment]
I've been thinking about this, and I currently think that it should be a different kind of pause shortcut. At the moment, ShowMIDI pauses everything with the spacebar, maybe a modifier + spacebar puts the continuous messages in 'collection' mode, where it keeps collecting the new ones from then on and displaying the latest value. Thoughts?

**Comment by essej** [comment]
That’s ok, but I’m not a fan of hiding such important behavior (both kinds of pause) behind only shortcut keybindings. I think you can spare the space for a few small buttons in the corner for this too.

**Comment by gbevin** [comment]
Ah good call out, I forgot about the side panel in the new UI, there can definitely be buttons there. Thanks!
