### ISSUE TITLE
Option to have program always on top

### ISSUE THREAD

**Issue by multivac61** [gbevin/ShowMIDI#7]

**Comment by dromer** [comment]
Wouldn't this be a feature of your OS/Window Manager? (ie. on Linux this is a common option)

When running as a plugin the host/DAW will take control over the window, so modifying any such properties is likely not be allowed (ready to be proven wrong though :) ).

**Comment by gbevin** [comment]
He likely wants it for the standalone app and I agree it's a great option. On macOS and Windows it's not that easy to make certain windows stick on top of others.

**Comment by multivac61** [comment]
Yes. Standalone mode on macOS. Would be tremendously useful 👍

**Comment by gbevin** [comment]
Added as option in next release
