### ISSUE TITLE
custom install path for VST2 on Windows

### ISSUE THREAD

**Issue by markusschloesser** [gbevin/ShowMIDI#8]
currently the plugin install to C:\Program Files\Common Files\VST, however this is not the most common path for VST2 plugins on Windows (which is C:\Program Files\vstplugins ). 
But even this is not a universal thing. Mine is at C:\Program Files\vstplugins 64. 

Could we have a custom install path and also ideally there is a way to ask Windows for (in Registry) set VST plugin folder. So if this setting, if existing, could be recognized?

BTW Thanks for the great tool!! :-)

**Comment by gbevin** [comment]
Added for next release
